import { promises as fs } from 'node:fs';
import path from 'node:path';
import {
  listIdentityProfiles,
  readActiveMetabotHome,
  type IdentityProfileRecord,
} from '../identity/identityProfiles';
import { resolveProfileNameMatch } from '../identity/profileNameResolution';

const OWNERSHIP_MARKER = '# Generated by Open Agent Connect. Do not edit.';
const PROFILE_MARKER_PREFIX = '# OAC MetaBot profile: ';
const PERSONA_FILES = ['ROLE.md', 'SOUL.md', 'GOAL.md'] as const;

export type HostPersonaProjectionState = 'unbound' | 'current' | 'stale' | 'conflict';

export interface HostPersonaProjectionInput {
  systemHomeDir: string;
  host: 'codex';
  from?: string;
  env?: NodeJS.ProcessEnv;
}

export interface HostPersonaProjectionResult {
  host: 'codex';
  profile: { name: string; slug: string; homeDir: string };
  agentName: string;
  agentFilePath: string;
  sourceFiles: string[];
  state: HostPersonaProjectionState;
}

export interface BindHostPersonaProjectionResult extends HostPersonaProjectionResult {
  action: 'created' | 'updated' | 'unchanged';
}

export interface UnbindHostPersonaProjectionResult extends HostPersonaProjectionResult {
  removed: boolean;
}

export class HostPersonaProjectionError extends Error {
  code:
    | 'identity_profile_not_found'
    | 'identity_profile_ambiguous'
    | 'active_identity_missing'
    | 'host_persona_source_missing'
    | 'host_persona_conflict'
    | 'host_persona_projection_failed';
  data: Record<string, unknown>;

  constructor(code: HostPersonaProjectionError['code'], message: string, data: Record<string, unknown> = {}) {
    super(message);
    this.name = 'HostPersonaProjectionError';
    this.code = code;
    this.data = data;
  }
}

function resolveCodexHome(systemHomeDir: string, env: NodeJS.ProcessEnv): string {
  const configured = env.CODEX_HOME?.trim();
  return configured ? path.resolve(configured) : path.join(path.resolve(systemHomeDir), '.codex');
}

async function resolveProfile(input: HostPersonaProjectionInput): Promise<IdentityProfileRecord> {
  const profiles = await listIdentityProfiles(input.systemHomeDir);
  if (input.from?.trim()) {
    const resolution = resolveProfileNameMatch(input.from, profiles);
    if (resolution.status === 'matched') {
      return resolution.match;
    }
    throw new HostPersonaProjectionError(
      resolution.status === 'ambiguous' ? 'identity_profile_ambiguous' : 'identity_profile_not_found',
      resolution.message,
      resolution.status === 'ambiguous'
        ? { from: input.from, candidates: resolution.candidates.map((profile) => profile.slug) }
        : { from: input.from },
    );
  }

  const activeHomeDir = await readActiveMetabotHome(input.systemHomeDir);
  const activeProfile = activeHomeDir
    ? profiles.find((profile) => path.resolve(profile.homeDir) === path.resolve(activeHomeDir))
    : undefined;
  if (!activeProfile) {
    throw new HostPersonaProjectionError(
      'active_identity_missing',
      'No active local MetaBot identity is available. Pass --from <bot-slug> or assign an active identity first.',
    );
  }
  return activeProfile;
}

async function readOptionalFile(filePath: string): Promise<string> {
  try {
    return (await fs.readFile(filePath, 'utf8')).trim();
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return '';
    }
    throw error;
  }
}

function compactDescription(value: string, fallback: string): string {
  const compact = value.replace(/^#+\s+.*$/gm, '').replace(/\s+/g, ' ').trim() || fallback;
  return compact.length <= 240 ? compact : `${compact.slice(0, 237).trimEnd()}...`;
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function normalizePersonaSection(value: string, heading: string): string {
  const lines = value.split('\n');
  if (new RegExp(`^#{1,6}\\s+${heading}\\s*$`, 'i').test(lines[0]?.trim() ?? '')) {
    return lines.slice(1).join('\n').trim();
  }
  return value;
}

async function compileProjection(input: HostPersonaProjectionInput): Promise<{
  profile: IdentityProfileRecord;
  agentFilePath: string;
  sourceFiles: string[];
  content: string;
}> {
  const target = await resolveProjectionTarget(input);
  const { profile, sourceFiles } = target;
  const [rawRole, rawSoul, rawGoal, bio] = await Promise.all([
    ...sourceFiles.map((filePath) => readOptionalFile(filePath)),
    readOptionalFile(path.join(profile.homeDir, 'BIO.md')),
  ]);
  const role = normalizePersonaSection(rawRole, 'Role');
  const soul = normalizePersonaSection(rawSoul, 'Soul');
  const goal = normalizePersonaSection(rawGoal, 'Goal');
  if (![role, soul, goal].some(Boolean)) {
    throw new HostPersonaProjectionError(
      'host_persona_source_missing',
      `Profile "${profile.name}" has no persona content in ROLE.md, SOUL.md, or GOAL.md.`,
      { profileSlug: profile.slug, sourceFiles },
    );
  }

  const description = compactDescription(
    bio,
    `Use ${profile.name} for tasks that benefit from this MetaBot's role, personality, and goal.`,
  );
  const instructions = [
    `You are operating as the local MetaBot persona named ${profile.name}.`,
    '',
    'This persona is an identity and behavior overlay for Codex. Keep Codex host capabilities intact.',
    '',
    '## Role',
    role || '(Not specified.)',
    '',
    '## Soul',
    soul || '(Not specified.)',
    '',
    '## Goal',
    goal || '(Not specified.)',
    '',
    '## Host Execution Boundaries',
    '- Follow all system and developer instructions, including the workspace AGENTS.md.',
    '- Use the host\'s available skills, tools, MCP servers, sandbox, and approval policy normally.',
    '- This persona does not grant wallet, signing, chain-write, or other authority.',
    `- For identity-sensitive OAC commands, pass --from ${profile.slug} explicitly.`,
    '- Do not apply A2A private-chat skill restrictions to host-native Codex execution.',
  ].join('\n');
  const content = [
    OWNERSHIP_MARKER,
    `${PROFILE_MARKER_PREFIX}${profile.slug}`,
    `name = ${tomlString(profile.name)}`,
    `description = ${tomlString(description)}`,
    `developer_instructions = ${tomlString(instructions)}`,
    '',
  ].join('\n');
  return { ...target, content };
}

async function resolveProjectionTarget(input: HostPersonaProjectionInput): Promise<{
  profile: IdentityProfileRecord;
  agentFilePath: string;
  sourceFiles: string[];
}> {
  const profile = await resolveProfile(input);
  return {
    profile,
    agentFilePath: path.join(
      resolveCodexHome(input.systemHomeDir, input.env ?? process.env),
      'agents',
      `metabot-${profile.slug}.toml`,
    ),
    sourceFiles: PERSONA_FILES.map((name) => path.join(profile.homeDir, name)),
  };
}

function isOwnedProjection(content: string, profileSlug: string): boolean {
  return content.includes(OWNERSHIP_MARKER) && content.includes(`${PROFILE_MARKER_PREFIX}${profileSlug}`);
}

async function readExistingProjection(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null;
    }
    throw error;
  }
}

function toBaseResult(
  compiled: Awaited<ReturnType<typeof resolveProjectionTarget>>,
  state: HostPersonaProjectionState,
): HostPersonaProjectionResult {
  return {
    host: 'codex',
    profile: {
      name: compiled.profile.name,
      slug: compiled.profile.slug,
      homeDir: compiled.profile.homeDir,
    },
    agentName: compiled.profile.name,
    agentFilePath: compiled.agentFilePath,
    sourceFiles: compiled.sourceFiles,
    state,
  };
}

async function inspectCompiledProjection(
  compiled: Awaited<ReturnType<typeof compileProjection>>,
): Promise<{ existing: string | null; state: HostPersonaProjectionState }> {
  const existing = await readExistingProjection(compiled.agentFilePath);
  if (existing === null) return { existing, state: 'unbound' };
  if (!isOwnedProjection(existing, compiled.profile.slug)) return { existing, state: 'conflict' };
  return { existing, state: existing === compiled.content ? 'current' : 'stale' };
}

export async function getHostPersonaProjectionStatus(
  input: HostPersonaProjectionInput,
): Promise<HostPersonaProjectionResult> {
  const target = await resolveProjectionTarget(input);
  const existing = await readExistingProjection(target.agentFilePath);
  if (existing === null) {
    return toBaseResult(target, 'unbound');
  }
  if (!isOwnedProjection(existing, target.profile.slug)) {
    return toBaseResult(target, 'conflict');
  }
  try {
    const compiled = await compileProjection(input);
    return toBaseResult(compiled, existing === compiled.content ? 'current' : 'stale');
  } catch (error) {
    if (error instanceof HostPersonaProjectionError && error.code === 'host_persona_source_missing') {
      return toBaseResult(target, 'stale');
    }
    throw error;
  }
}

export async function bindHostPersonaProjection(
  input: HostPersonaProjectionInput,
): Promise<BindHostPersonaProjectionResult> {
  const compiled = await compileProjection(input);
  const inspected = await inspectCompiledProjection(compiled);
  if (inspected.state === 'conflict') {
    throw new HostPersonaProjectionError(
      'host_persona_conflict',
      `Refusing to overwrite a Codex agent file not owned by OAC: ${compiled.agentFilePath}`,
      { agentFilePath: compiled.agentFilePath, profileSlug: compiled.profile.slug },
    );
  }
  if (inspected.state === 'current') {
    return { ...toBaseResult(compiled, 'current'), action: 'unchanged' };
  }

  const directory = path.dirname(compiled.agentFilePath);
  const temporaryPath = `${compiled.agentFilePath}.tmp-${process.pid}-${Date.now()}`;
  try {
    await fs.mkdir(directory, { recursive: true });
    await fs.writeFile(temporaryPath, compiled.content, { encoding: 'utf8', mode: 0o600 });
    await fs.rename(temporaryPath, compiled.agentFilePath);
  } catch (error) {
    await fs.rm(temporaryPath, { force: true }).catch(() => undefined);
    throw new HostPersonaProjectionError(
      'host_persona_projection_failed',
      `Unable to write the Codex persona projection: ${compiled.agentFilePath}`,
      { agentFilePath: compiled.agentFilePath, reason: error instanceof Error ? error.message : String(error) },
    );
  }
  return {
    ...toBaseResult(compiled, 'current'),
    action: inspected.state === 'unbound' ? 'created' : 'updated',
  };
}

export async function unbindHostPersonaProjection(
  input: HostPersonaProjectionInput,
): Promise<UnbindHostPersonaProjectionResult> {
  const target = await resolveProjectionTarget(input);
  const existing = await readExistingProjection(target.agentFilePath);
  if (existing !== null && !isOwnedProjection(existing, target.profile.slug)) {
    throw new HostPersonaProjectionError(
      'host_persona_conflict',
      `Refusing to remove a Codex agent file not owned by OAC: ${target.agentFilePath}`,
      { agentFilePath: target.agentFilePath, profileSlug: target.profile.slug },
    );
  }
  if (existing === null) {
    return { ...toBaseResult(target, 'unbound'), removed: false };
  }
  try {
    await fs.rm(target.agentFilePath);
  } catch (error) {
    throw new HostPersonaProjectionError(
      'host_persona_projection_failed',
      `Unable to remove the Codex persona projection: ${target.agentFilePath}`,
      { agentFilePath: target.agentFilePath, reason: error instanceof Error ? error.message : String(error) },
    );
  }
  return { ...toBaseResult(target, 'unbound'), removed: true };
}
